version: 2.1

jobs:
  build:
    parameters:
      php_version:
        type: string
      dependency:
        type: string
        default: stable

    docker:
      - image: cimg/php:<< parameters.php_version >>

    resource_class: small

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v1-{{ .Branch }}-{{ checksum "composer.json" }}
            - composer-v1-{{ .Branch }}-

      - run: sudo composer self-update --2

      - run: composer update -n --prefer-dist --prefer-stable --prefer-<< parameters.dependency >>

      - save_cache:
          key: composer-v1-{{ .Branch }}-{{ checksum "composer.json" }}
          paths:
            - ~/.cache/composer

      - run: ./vendor/bin/phpunit

  code-style:
    docker:
      - image: cimg/php:8.1

    resource_class: small

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v1-{{ .Branch }}-{{ checksum "composer.json" }}
            - composer-v1-{{ .Branch }}-

      - run: sudo composer self-update --2

      - run: composer global require "squizlabs/php_codesniffer"

      - run: composer global update -n --prefer-dist --prefer-stable

      - save_cache:
          key: composer-v1-{{ .Branch }}-{{ checksum "composer.json" }}
          paths:
            - ~/.cache/composer

      - run: phpcs -n src/ tests/

workflows:
  workflow:
    jobs:
      - build:
          name: build-<< matrix.php_version >>-<< matrix.dependency >>
          matrix:
            parameters:
              php_version: ["7.3", "7.4", "8.0", "8.1"]
              dependency: ["stable"]
      - code-style:
          name: code-style

